### ISSUE TITLE
Issue when compiling with iOS 9 SDK

### ISSUE THREAD

**Issue by notd3vdev** [theos/sdks#18] opened 2018-07-18 00:52 UTC
I have ldid installed, and I'm using iOS 9 SDK with Linux, and I get this error
It happens with architecture set to armv7 and arm64
```
ld: file not found: /usr/lib/system/liblaunch.dylib for architecture arm64
arm64-apple-darwin14-clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
/opt/theos/makefiles/instance/library.mk:32: recipe for target '/home/test/.theos/obj/debug/arm64/Test.dylib' failed
make[3]: *** [/home/test/.theos/obj/debug/arm64/Test.dylib] Error 1
/opt/theos/makefiles/instance/library.mk:32: recipe for target '/home/test/.theos/obj/debug/arm64/Test.dylib' failed
make[2]: *** [/home/test/.theos/obj/debug/arm64/Test.dylib] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by yur1xpp** [comment] 2018-07-18 03:10
I got the same issue on WSL too.

**Comment by drewsucksatlife** [comment] 2018-07-21 22:51
I get this issue as well.

**Comment by kirb** [comment] 2018-07-22 05:08
Duplicate of #10. Let’s keep this in the one thread.

**Closed by kirb** 2018-07-22 05:08 UTC
