### ISSUE TITLE
Error while running make.

### ISSUE THREAD

**Issue by drewsucksatlife** [theos/sdks#16] opened 2018-07-16 03:57 UTC
Whenever I run, `make`, on linux, within my tweak directory, I get the following error:
```
> Making all for tweak Test…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
While building module 'Foundation' imported from /opt/theos/Prefix.pch:11:
In file included from <module-includes>:2:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:128:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUUID.h:26:49: error: nullability specifier '_Nullable' cannot be applied to non-pointer type 'uuid_t' (aka 'unsigned char [16]')
- (instancetype)initWithUUIDBytes:(const uuid_t _Nullable)bytes;
                                                ^
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUUID.h:29:30: error: nullability specifier '_Nonnull' cannot be applied to non-pointer type 'uuid_t' (aka 'unsigned char [16]')
- (void)getUUIDBytes:(uuid_t _Nonnull)uuid;
                             ^
In file included from <built-in>:1:
/opt/theos/Prefix.pch:11:11: fatal error: could not build module 'Foundation'
                #import <Foundation/Foundation.h>
                 ~~~~~~~^
While building module 'UIKit' imported from /opt/theos/Prefix.pch:20:
In file included from <module-includes>:2:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:11:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAccelerometer.h:8:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
While building module 'UIKit' imported from /opt/theos/Prefix.pch:20:
While building module 'QuartzCore' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:9:
In file included from <module-includes>:1:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/QuartzCore.h:9:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CoreAnimation.h:10:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CATransform3D.h:12:9: fatal error: could not build module 'Foundation'
#import <Foundation/NSValue.h>
 ~~~~~~~^
While building module 'UIKit' imported from /opt/theos/Prefix.pch:20:
While building module 'QuartzCore' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:9:
While building module 'OpenGLES' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAEAGLLayer.h:7:
In file included from <module-includes>:8:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGLDrawable.h:8:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: fatal error: could not build module 'Foundation'
#include <Foundation/Foundation.h>
 ~~~~~~~~^
While building module 'UIKit' imported from /opt/theos/Prefix.pch:20:
While building module 'QuartzCore' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:9:
While building module 'OpenGLES' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAEAGLLayer.h:7:
While building module 'IOSurface' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGLIOSurface.h:13:
In file included from <module-includes>:8:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/IOSurface.framework/Headers/IOSurfaceObjC.h:15:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
While building module 'UIKit' imported from /opt/theos/Prefix.pch:20:
While building module 'QuartzCore' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:9:
While building module 'Metal' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:7:
In file included from <module-includes>:2:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:9:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTypes.h:8:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
While building module 'UIKit' imported from /opt/theos/Prefix.pch:20:
While building module 'CoreImage' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIColor.h:11:
In file included from <module-includes>:2:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImage.h:9:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
While building module 'UIKit' imported from /opt/theos/Prefix.pch:20:
While building module 'CoreImage' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIColor.h:11:
While building module 'CoreVideo' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:10:
In file included from <module-includes>:2:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:29:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVPixelBuffer.h:461:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVPixelBufferIOSurface.h:26:10: fatal error: could not build module 'IOSurface'
#include <IOSurface/IOSurfaceRef.h>
 ~~~~~~~~^
While building module 'UIKit' imported from /opt/theos/Prefix.pch:20:
While building module 'FileProvider' imported from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSFileProviderExtension.h:14:
In file included from <module-includes>:1:
In file included from /opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/FileProvider.framework/Headers/FileProvider.h:8:
/opt/theos/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:8:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
11 errors generated.
/opt/theos/makefiles/instance/rules.mk:245: recipe for target '/home/drew/test/.theos/obj/debug/arm64/Tweak.xm.ba70a9a6.o' failed
make[3]: *** [/home/drew/test/.theos/obj/debug/arm64/Tweak.xm.ba70a9a6.o] Error 1
/opt/theos/makefiles/instance/library.mk:32: recipe for target '/home/drew/test/.theos/obj/debug/arm64/Test.dylib' failed
make[2]: *** [/home/drew/test/.theos/obj/debug/arm64/Test.dylib] Error 2
/opt/theos/makefiles/instance/library.mk:24: recipe for target 'internal-library-all_' failed
make[1]: *** [internal-library-all_] Error 2
/opt/theos/makefiles/master/rules.mk:123: recipe for target 'Test.all.tweak.variables' failed
make: *** [Test.all.tweak.variables] Error 2
```

**Comment by kirb** [comment] 2018-07-16 09:18
Duplicate of #13.

**Closed by kirb** 2018-07-16 09:18 UTC
